### ISSUE TITLE
Incorrect Padding

### ISSUE THREAD

**Issue by flamendless** [EngineerSmith/Export-TextureAtlas#2]
Free-tex-packer:
![image](https://user-images.githubusercontent.com/17418737/143670444-670df788-3976-499d-a52c-d79da25a9474.png)
here you can see a padding of 4 per quad, so total would be 8 for neighboring quads

Export-TextureAtlas:
![image](https://user-images.githubusercontent.com/17418737/143670428-dd606960-f5c3-4070-8575-b67f18553206.png)
here you can see a padding of 4 per quad but is shared between neighboring quads so resulting to only 2 pixels per quad

**Comment by EngineerSmith** [comment]
This is expected behaviour, but I can understand why it shouldn't be. CSS padding puts it around each object whilst the code defines padding as spacing between each object. Unsure if the solution should be to rename the variable, or change the behaviour

**Comment by flamendless** [comment]
Either:
* just multiply the padding by two internally?
* have a note or comment in the readme about the behavior of padding?

**Comment by EngineerSmith** [comment]
I'll change it. I'll have spacing to do the current behaviour, whilst padding will add spacing around an object (currently the atlas fits closely to the edge of the texture, but padding will force a gap between the edge and the quad)

**Comment by flamendless** [comment]
Awesome. spacing and padding sound perfect.

>  (currently the atlas fits closely to the edge of the texture, but padding will force a gap between the edge and the quad)

indeed, in free-tex-packer, setting padding will also add padding in the edges of the atlas

Just an info, im using padding in combination with an [outlining shader](https://love2d.org/forums/viewtopic.php?p=221215#p221215) (though mine is heavily modified) for my project

**Comment by flamendless** [comment]
I tested the latest commit [1b2171bb45f637d2ad154f9387931993791325a3](https://github.com/EngineerSmith/Runtime-TextureAtlas/commit/1b2171bb45f637d2ad154f9387931993791325a3) the padding works but the data is not correct.
The x and y of the quad should use (4, 4) lets say instead of (0, 0) if padding is 4.

**Comment by EngineerSmith** [comment]
Good to know. Github died last night for a couple of hours just as I was pulling, so I wasn't able to work too much on it

**Comment by EngineerSmith** [comment]
This should be fixed with [133d8e886101a4ae700b6514afe3b198d67f270a](https://github.com/EngineerSmith/Runtime-TextureAtlas/commit/133d8e886101a4ae700b6514afe3b198d67f270a) now. It was only an issue with dynamic atlases. Reopen if you find fault with it
